# Generated by Django 4.2.5 on 2023-10-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistic',
            fields=[
                ('Logistic_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Accuracy', models.TextField(max_length=100)),
                ('Precession', models.TextField(max_length=100)),
                ('F1_Score', models.TextField(max_length=100)),
                ('Recall', models.TextField(max_length=100)),
                ('Name', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'Logistic',
            },
        ),
        migrations.CreateModel(
            name='RandomForest',
            fields=[
                ('Random_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Accuracy', models.TextField(max_length=100)),
                ('Precession', models.TextField(max_length=100)),
                ('F1_Score', models.TextField(max_length=100)),
                ('Recall', models.TextField(max_length=100)),
                ('Name', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'RandomForest',
            },
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='BMI',
            new_name='TEST_RESULTS',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='BloodPressure',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='DiabetesPedigreeFunction',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='Glucose',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='Insulin',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='SkinThickness',
        ),
        migrations.AddField(
            model_name='dataset',
            name='PHYSICAL_SCORE',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
