# Generated by Django 4.2.5 on 2023-10-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserHearingDetectionModels',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_dates', models.DateField(auto_now_add=True)),
                ('user_username', models.TextField(max_length=50, null=True)),
                ('user_email', models.TextField(max_length=50, null=True)),
                ('user_password', models.TextField(max_length=50, null=True)),
                ('user_contact', models.TextField(max_length=50, null=True)),
                ('user_file', models.FileField(null=True, upload_to='images')),
                ('user_status', models.TextField(default='pending', max_length=30, null=True)),
                ('otp_status', models.TextField(default='pending', max_length=20)),
                ('otp', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'hearing_table',
            },
        ),
    ]
