# Generated by Django 4.2.5 on 2023-10-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last_login',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Login_Time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'last_login',
            },
        ),
        migrations.AddField(
            model_name='userhearingdetectionmodels',
            name='Last_Login_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userhearingdetectionmodels',
            name='Last_Login_Time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='userhearingdetectionmodels',
            name='No_Of_Times_Login',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
